name: skip-kit
on:
  push:
    branches: [ main ]
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 8,22 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  call-workflow:
    uses: skiptools/actions/.github/workflows/skip-framework.yml@main
    with:
      # disable local tests because SkipFuseUI requires macOS 14+
      run-local-tests: false

